-- Migration 020: Billing Schema Stabilization
-- Establishes all columns, tables, and indexes required by the billing backend.
-- No existing data is removed. All changes are purely additive.
--
-- Root cause: migrations 011 (billing tables) and 012 (settings) existed, but
-- several columns expected by backend code (billing.js, orderCompletion.js,
-- paymentProviders.js, admin.js) were never formalised in any migration:
--   • orders.checkout_url, provider_reference, failure_reason, failure_code,
--     last_payment_event_at  — written on every payment flow
--   • credit_packages.is_featured, description, features — read by /api/billing/packages
--   • payment_providers table — queried/upserted by the full provider registry
--   • system_settings.credits_per_page, credits_per_enrichment, credits_per_lead,
--     google_maps_api_key, smtp_* — read at runtime, never migrated
--
-- This migration makes those assumptions explicit and safe.


-- ============================================================================
-- 1. ORDERS — extended billing fields
-- ============================================================================
-- These columns are written by billing.js on every payment flow (provider init,
-- callback, webhook). They must exist for the billing pipeline to function.

DO $$
BEGIN
    -- Checkout / redirect URL generated by the payment gateway
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns
                   WHERE table_schema = 'public'
                   AND table_name = 'orders'
                   AND column_name = 'checkout_url') THEN
        ALTER TABLE public.orders ADD COLUMN checkout_url TEXT;
    END IF;

    -- Opaque reference string returned by the payment gateway (e.g. PayTR merchant_oid)
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns
                   WHERE table_schema = 'public'
                   AND table_name = 'orders'
                   AND column_name = 'provider_reference') THEN
        ALTER TABLE public.orders ADD COLUMN provider_reference TEXT;
    END IF;

    -- Human-readable failure reason set by failOrder() or callback handlers
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns
                   WHERE table_schema = 'public'
                   AND table_name = 'orders'
                   AND column_name = 'failure_reason') THEN
        ALTER TABLE public.orders ADD COLUMN failure_reason TEXT;
    END IF;

    -- Machine-readable provider error code (e.g. iyzico error code)
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns
                   WHERE table_schema = 'public'
                   AND table_name = 'orders'
                   AND column_name = 'failure_code') THEN
        ALTER TABLE public.orders ADD COLUMN failure_code TEXT;
    END IF;

    -- Timestamp of the most recent payment lifecycle event (init/callback/webhook)
    -- Enables admins to see stale pending orders and diagnose partial failures.
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns
                   WHERE table_schema = 'public'
                   AND table_name = 'orders'
                   AND column_name = 'last_payment_event_at') THEN
        ALTER TABLE public.orders ADD COLUMN last_payment_event_at TIMESTAMPTZ;
    END IF;
END $$;

-- Index to support admin queries filtering / sorting by provider reference
CREATE INDEX IF NOT EXISTS idx_orders_provider_reference
    ON public.orders(provider_reference)
    WHERE provider_reference IS NOT NULL;

-- Index to support admin overview queries for stale pending orders
CREATE INDEX IF NOT EXISTS idx_orders_last_event_at
    ON public.orders(last_payment_event_at DESC)
    WHERE last_payment_event_at IS NOT NULL;


-- ============================================================================
-- 2. CREDIT PACKAGES — display/marketing extended fields
-- ============================================================================
-- The /api/billing/packages endpoint explicitly selects is_featured, description,
-- and features from the DB. These columns must exist even when unused.

DO $$
BEGIN
    -- Flag used by the billing page to render a "Most Popular" badge
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns
                   WHERE table_schema = 'public'
                   AND table_name = 'credit_packages'
                   AND column_name = 'is_featured') THEN
        ALTER TABLE public.credit_packages ADD COLUMN is_featured BOOLEAN NOT NULL DEFAULT false;
    END IF;

    -- Short marketing description text for the billing page card
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns
                   WHERE table_schema = 'public'
                   AND table_name = 'credit_packages'
                   AND column_name = 'description') THEN
        ALTER TABLE public.credit_packages ADD COLUMN description TEXT;
    END IF;

    -- JSONB array of bullet-point feature strings rendered on the billing page
    -- e.g. ["10,000 contacts", "Export to Excel", "Priority support"]
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns
                   WHERE table_schema = 'public'
                   AND table_name = 'credit_packages'
                   AND column_name = 'features') THEN
        ALTER TABLE public.credit_packages ADD COLUMN features JSONB;
    END IF;
END $$;

-- Mark the middle tier as the default featured package (safe idempotent update)
UPDATE public.credit_packages
SET is_featured = true
WHERE name = 'growth' AND is_featured = false;


-- ============================================================================
-- 3. PAYMENT PROVIDERS TABLE
-- ============================================================================
-- The full payment provider registry (PayTR, iyzico, Shopier, Stripe,
-- bank_transfer). paymentProviders.js assumes this table exists and upserts
-- into it. The admin UI reads/writes every field listed here.

CREATE TABLE IF NOT EXISTS public.payment_providers (
    id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    provider_code       TEXT NOT NULL UNIQUE,   -- 'paytr' | 'iyzico' | 'shopier' | 'stripe' | 'bank_transfer'
    display_name        TEXT NOT NULL,
    enabled             BOOLEAN NOT NULL DEFAULT false,
    mode                TEXT NOT NULL DEFAULT 'test',  -- 'test' | 'live'
    region              TEXT NOT NULL DEFAULT 'tr',    -- 'tr' | 'global'
    supported_currencies TEXT[] NOT NULL DEFAULT ARRAY['TRY'],

    -- Generic gateway credentials
    merchant_id         TEXT,
    api_key             TEXT,
    secret_key          TEXT,       -- !! NEVER forwarded to client !!
    public_key          TEXT,       -- e.g. Stripe publishable key
    webhook_secret      TEXT,       -- !! NEVER forwarded to client !!

    -- Provider-specific extension fields
    extra_config        JSONB,      -- Any provider-specific config that doesn't fit above

    -- Bank transfer specific (bank_transfer provider only)
    bank_name           TEXT,
    account_holder      TEXT,
    iban                TEXT,
    payment_note        TEXT,

    sort_order          INTEGER NOT NULL DEFAULT 0,
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Indexes for the admin provider list and gateway lookups
CREATE INDEX IF NOT EXISTS idx_payment_providers_code
    ON public.payment_providers(provider_code);
CREATE INDEX IF NOT EXISTS idx_payment_providers_enabled
    ON public.payment_providers(enabled)
    WHERE enabled = true;

-- RLS: Admin-only write access; the backend always uses the service-role key
-- so RLS on the server side is bypassed automatically.
ALTER TABLE public.payment_providers ENABLE ROW LEVEL SECURITY;

-- Block all direct anon/user reads — only service-role (backend) can read
CREATE POLICY IF NOT EXISTS "Block client access to payment_providers"
    ON public.payment_providers
    FOR ALL
    USING (false)
    WITH CHECK (false);

-- Seed default provider rows (safe: ON CONFLICT (provider_code) DO NOTHING)
INSERT INTO public.payment_providers
    (provider_code, display_name, enabled, mode, region, supported_currencies, sort_order)
VALUES
    ('paytr',         'PayTR',        false, 'test', 'tr',     ARRAY['TRY'], 1),
    ('iyzico',        'iyzico',       false, 'test', 'tr',     ARRAY['TRY'], 2),
    ('shopier',       'Shopier',      false, 'test', 'tr',     ARRAY['TRY'], 3),
    ('stripe',        'Stripe',       false, 'test', 'global', ARRAY['USD', 'EUR'], 4),
    ('bank_transfer', 'IBAN / Havale',false, 'live', 'tr',     ARRAY['TRY'], 5)
ON CONFLICT (provider_code) DO NOTHING;


-- ============================================================================
-- 4. SYSTEM SETTINGS — credit rate and API key fields
-- ============================================================================
-- Runtime billing and search code reads these columns from system_settings id=1.
-- They must exist for the system to function correctly at boot.

DO $$
BEGIN
    -- Credit rate per record returned from Google Maps (used in search billing)
    -- Named credits_per_page for backwards compatibility with existing code comment.
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns
                   WHERE table_schema = 'public'
                   AND table_name = 'system_settings'
                   AND column_name = 'credits_per_page') THEN
        ALTER TABLE public.system_settings ADD COLUMN credits_per_page INTEGER NOT NULL DEFAULT 1;
    END IF;

    -- Credit rate per enrichment operation (phone/email lookup)
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns
                   WHERE table_schema = 'public'
                   AND table_name = 'system_settings'
                   AND column_name = 'credits_per_enrichment') THEN
        ALTER TABLE public.system_settings ADD COLUMN credits_per_enrichment INTEGER NOT NULL DEFAULT 1;
    END IF;

    -- Legacy alias: credits_per_lead (same concept, kept for any older admin code)
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns
                   WHERE table_schema = 'public'
                   AND table_name = 'system_settings'
                   AND column_name = 'credits_per_lead') THEN
        ALTER TABLE public.system_settings ADD COLUMN credits_per_lead INTEGER NOT NULL DEFAULT 1;
    END IF;

    -- Google Maps Places API key (required for search functionality)
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns
                   WHERE table_schema = 'public'
                   AND table_name = 'system_settings'
                   AND column_name = 'google_maps_api_key') THEN
        ALTER TABLE public.system_settings ADD COLUMN google_maps_api_key TEXT;
    END IF;

    -- SMTP configuration (used by email/notification systems)
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns
                   WHERE table_schema = 'public'
                   AND table_name = 'system_settings'
                   AND column_name = 'smtp_host') THEN
        ALTER TABLE public.system_settings ADD COLUMN smtp_host TEXT;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM information_schema.columns
                   WHERE table_schema = 'public'
                   AND table_name = 'system_settings'
                   AND column_name = 'smtp_port') THEN
        ALTER TABLE public.system_settings ADD COLUMN smtp_port INTEGER NOT NULL DEFAULT 587;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM information_schema.columns
                   WHERE table_schema = 'public'
                   AND table_name = 'system_settings'
                   AND column_name = 'smtp_user') THEN
        ALTER TABLE public.system_settings ADD COLUMN smtp_user TEXT;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM information_schema.columns
                   WHERE table_schema = 'public'
                   AND table_name = 'system_settings'
                   AND column_name = 'smtp_pass') THEN
        ALTER TABLE public.system_settings ADD COLUMN smtp_pass TEXT;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM information_schema.columns
                   WHERE table_schema = 'public'
                   AND table_name = 'system_settings'
                   AND column_name = 'smtp_from') THEN
        ALTER TABLE public.system_settings ADD COLUMN smtp_from TEXT;
    END IF;
END $$;


-- ============================================================================
-- 5. CREDIT LEDGER — order reference alignment
-- ============================================================================
-- credit_ledger tracks all credit movements. Order completion writes rows here
-- without an order_id FK (compatibility). Adding the optional reference column
-- moves us toward better traceability without breaking existing rows.

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns
                   WHERE table_schema = 'public'
                   AND table_name = 'credit_ledger'
                   AND column_name = 'order_id') THEN
        ALTER TABLE public.credit_ledger ADD COLUMN order_id UUID REFERENCES public.orders(id) ON DELETE SET NULL;
    END IF;

    -- Source label: 'billing' | 'search' | 'export' | 'admin_adjust' | 'admin_grant'
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns
                   WHERE table_schema = 'public'
                   AND table_name = 'credit_ledger'
                   AND column_name = 'source') THEN
        ALTER TABLE public.credit_ledger ADD COLUMN source TEXT;
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_credit_ledger_order_id
    ON public.credit_ledger(order_id)
    WHERE order_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_credit_ledger_type
    ON public.credit_ledger(type);
